[package]
name = "djot-log"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.34"
clap = { version = "4.5.0", features = ["derive"] }
env_logger = "0.11.1"
frozenset = "0.2.2"
itertools = "0.12.1"
log = "0.4.20"
markdown = "1.0.0-alpha.16"
